### ISSUE TITLE
[Question] tthe link of the pre-trained vision tokenizer weight cannot be opened?

### ISSUE THREAD

**Issue by weineuro** [YifanXu74/Libra#1]
### Question

Hi, It seems the URL for the pre-trained vision tokenizer weight is not correct. Where can I download the related files: 'vision_tokenizer_config.yaml' and  'vqgan.ckpt'?

**Comment by YifanXu74** [comment]
Oh sorry for that. I've fixed the link in the updated readme. Please refer to [here](https://huggingface.co/YifanXu/libra-vision-tokenizer).

**Comment by weineuro** [comment]
Great, thanks~
