### ISSUE TITLE
[Question] The usage of datasets during pre-training

### ISSUE THREAD

**Issue by CyrilSterling** [YifanXu74/Libra#5]
### Question

Thanks for your impressive work!
I just have a question about the datasets. The paper says "For pretraining, we use 50M image-text pairs randomly sampled from COYO-700M and CC12M . We use additional 500K image-text pairs from COCO training split to standardize the caption outputs". However, the code uses laion for pre-training. What is the difference in the choice of datasets?

**Comment by YifanXu74** [comment]
Hi @CyrilSterling ,

The code currently has support for datasets in webdataset format, such as LAION, COYO, and CC. The usage of 'laion' in the code only refers to all datasets in webdataset format, not a specific LAION dataset. In practice, we reorganized the sampled data and stored them in a new folder named 'laion'.

**Comment by CyrilSterling** [comment]
Thanks very much for your reply!
And could you open source the reorganized 'laion' folder?

**Comment by YifanXu74** [comment]
Oh, the data cannot be made open-sourced due to PCL's data management regulations. However, you can use any open-sourced image-text data like LAION and COYO.
